version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    tag: /release-.*/
    docker:
      - image: circleci/node:10.23.0
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run coverage
      - slack/notify:
          event: fail
          mentions: '@rhea-so'
          template: basic_fail_1
      - slack/notify:
          event: pass
          mentions: '@rhea-so'
          template: success_tagged_deploy_1
workflows:
  build-and-send-notification:
    jobs:
      - build
          context: slack-secrets